Update workflow

diff --git a/.github/workflows/publish-to-npm.yml b/.github/workflows/publish-to-npm.yml
--- a/.github/workflows/publish-to-npm.yml
+++ b/.github/workflows/publish-to-npm.yml
@@ -22,28 +22,28 @@ jobs:
           node-version: 22
           registry-url: 'https://registry.npmjs.org'
 
-      - name: Get current version
-        id: get_version
-        run: echo "CURRENT_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
-
-      - name: Fetch npm version
-        id: fetch_npm_version
+      - name: Get current version and package name
+        id: get_version_and_name
         run: |
-          npm_version=$(npm show @teampanfu/websockify version)
-          echo "NPM_VERSION=${npm_version}" >> $GITHUB_ENV
+          PACKAGE_NAME=$(node -p "require('./package.json').name")
+          CURRENT_VERSION=$(node -p "require('./package.json').version")
+          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
+          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
 
-      - name: Compare versions
-        id: compare_versions
+      - name: Fetch npm version and compare
         run: |
-          if [ "$CURRENT_VERSION" != "$NPM_VERSION" ]; then
-            echo "Version has changed."
+          NPM_VERSION=$(npm show ${PACKAGE_NAME} version || echo "not_found")
+          if [ "$NPM_VERSION" = "not_found" ]; then
+            echo "Package not found in registry. Proceeding with publish."
+          elif [ "$CURRENT_VERSION" != "$NPM_VERSION" ]; then
+            echo "Version has changed. Proceeding with publish."
           else
             echo "Version unchanged. Skipping publish."
             exit 0
           fi
         env:
+          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
           CURRENT_VERSION: ${{ env.CURRENT_VERSION }}
-          NPM_VERSION: ${{ env.NPM_VERSION }}
 
       - name: Install dependencies
         run: npm install
